# Generated by Django 4.1 on 2022-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationType', models.CharField(choices=[('Unknown', 'Unknown'), ('Lube', 'Lube'), ('Vacuum', 'Vacuum'), ('Washing', 'Washing')], default=0, max_length=200)),
                ('Camera', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('PlatesNo', models.CharField(blank=True, max_length=200, null=True)),
                ('PlatesRegion', models.CharField(blank=True, max_length=200, null=True)),
                ('PlatesScore', models.CharField(blank=True, max_length=200, null=True)),
                ('VehicleType', models.CharField(blank=True, max_length=200, null=True)),
                ('EntryTime', models.DateTimeField(blank=True, null=True)),
                ('ExitTime', models.DateTimeField(blank=True, null=True)),
                ('VehicleImage', models.FileField(blank=True, upload_to='Events/%Y/%m/%d/')),
                ('PlateImage', models.FileField(blank=True, upload_to='Events/%Y/%m/%d/')),
                ('LPRResult', models.CharField(blank=True, max_length=4096, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
